picom -b &
feh --bg-scale $HOME/Pictures/wallpapers/evening.jpg &
xinput --set-prop 'pointer:Glorious Model O' 'libinput Accel Profile Enabled' 0, 1 &
xinput --set-prop 'pointer:Glorious Model O' 'libinput Accel Speed' 0 &
bash $HOME/Scripts/date.sh
sxhkd &
exec dwm
